development:
  forest_env_secret: ffeb098c3b4a6da548db90b0fc0b7870af58ccf32ba614418ee9453625deb897
  forest_auth_secret: raWHihAaOO-W0uKzLYVLCg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
